SELECT *
FROM LAYOFF.LAYOFF_DATA;


ALTER LAYOFF.LAYOFF_DATA
ALTER COLUMN TOTAL_LAID_OFF TYPE INT USING TOTAL_LAID_OFF::INT
ALTER TABLE LAYOFF.LAYOFF_DATA
ALTER COLUMN PERCENTAGE_LAID_OFF TYPE FLOAT USING PERCENTAGE_LAID_OFF::FLOAT
ALTER TABLE LAYOFF.LAYOFF_DATA
ALTER COLUMN FUNDS_RAISED_MILLIONS TYPE NUMERIC USING FUNDS_RAISED_MILLIONS::NUMERIC
ALTER TABLE LAYOFF.LAYOFF_DATA
ALTER COLUMN DATE TYPE DATE USING DATE::DATE
CREATE TABLE LAYOFF.LAYOFF_WORK (LIKE LAYOFF.LAYOFF_DATA);


SELECT *
FROM LAYOFF.LAYOFF_WORK;

-- INSERT INTO layoff.layoff_work
-- SELECT * FROM layoff.layoff_data;

SELECT *,
       ROW_NUMBER() OVER (PARTITION BY COMPANY, LOCATION, INDUSTRY, TOTAL_LAID_OFF, PERCENTAGE_LAID_OFF, DATE, STAGE, COUNTRY, FUNDS_RAISED_MILLIONS) AS ROW_NUM
FROM LAYOFF.LAYOFF_WORK
ORDER BY ROW_NUM DESC WITH DUPLICATE_CTE AS
  (SELECT *,
          ROW_NUMBER() OVER (PARTITION BY COMPANY, LOCATION, INDUSTRY, TOTAL_LAID_OFF, PERCENTAGE_LAID_OFF, DATE, STAGE, COUNTRY, FUNDS_RAISED_MILLIONS
                             ORDER BY
                               (SELECT NULL)) AS ROW_NUM
   FROM LAYOFF.LAYOFF_WORK)
SELECT *
FROM DUPLICATE_CTE
WHERE ROW_NUM > 1;


CREATE TABLE LAYOFF.LAYOFF_WORK2 AS
SELECT *,
       ROW_NUMBER() OVER (PARTITION BY COMPANY, LOCATION, INDUSTRY, TOTAL_LAID_OFF, PERCENTAGE_LAID_OFF, DATE, STAGE, COUNTRY, FUNDS_RAISED_MILLIONS) AS ROW_NUM
FROM LAYOFF.LAYOFF_WORK
SELECT *
FROM LAYOFF.LAYOFF_WORK2;


SELECT *
FROM LAYOFF.LAYOFF_WORK2
ORDER BY ROW_NUM DESC;


DELETE
FROM LAYOFF.LAYOFF_WORK2
WHERE ROW_NUM > 1;


SELECT *
FROM LAYOFF.LAYOFF_WORK2
ORDER BY ROW_NUM DESC;


SELECT COMPANY
FROM LAYOFF.LAYOFF_WORK2;


UPDATE LAYOFF.LAYOFF_WORK2
SET COMPANY = TRIM(COMPANY);


SELECT INDUSTRY
FROM LAYOFF.LAYOFF_WORK2;


SELECT DISTINCT INDUSTRY
FROM LAYOFF.LAYOFF_WORK2;


SELECT INDUSTRY
FROM LAYOFF.LAYOFF_WORK2
WHERE INDUSTRY ILIKE 'crypto%';


UPDATE LAYOFF.LAYOFF_WORK2
SET INDUSTRY = 'Crypto'
WHERE INDUSTRY ILIKE 'crypto%'
  SELECT DISTINCT COUNTRY
  FROM LAYOFF.LAYOFF_WORK2;


UPDATE LAYOFF.LAYOFF_WORK2
SET COUNTRY = 'United States'
WHERE COUNTRY ILIKE 'united states%'
  SELECT DATE
  FROM LAYOFF.LAYOFF_WORK2;


SELECT *
FROM LAYOFF.LAYOFF_WORK2
WHERE TOTAL_LAID_OFF IS NULL
  AND PERCENTAGE_LAID_OFF IS NULL
  SELECT DISTINCT INDUSTRY
  FROM LAYOFF.LAYOFF_WORK2;


SELECT INDUSTRY
FROM LAYOFF.LAYOFF_WORK2
WHERE INDUSTRY IS NULL;


SELECT INDUSTRY
FROM LAYOFF.LAYOFF_WORK2
WHERE INDUSTRY IS NULL
  OR INDUSTRY = '';


SELECT *
FROM LAYOFF.LAYOFF_WORK2
WHERE INDUSTRY IS NULL
  OR INDUSTRY = '';


SELECT *
FROM LAYOFF.LAYOFF_WORK2
WHERE COMPANY = 'Airbnb';


UPDATE LAYOFF.LAYOFF_WORK2
SET INDUSTRY = NULL
WHERE INDUSTRY = ''
  OR INDUSTRY = 'NULL';


SELECT *
FROM LAYOFF.LAYOFF_WORK2 L1
JOIN LAYOFF.LAYOFF_WORK2 L2 ON L1.COMPANY = L2.COMPANY
WHERE L1.INDUSTRY IS NULL
  AND L2.INDUSTRY IS NOT NULL;


SELECT L1.INDUSTRY,
       L2.INDUSTRY
FROM LAYOFF.LAYOFF_WORK2 L1
JOIN LAYOFF.LAYOFF_WORK2 L2 ON L1.COMPANY = L2.COMPANY
WHERE L1.INDUSTRY IS NULL
  AND L2.INDUSTRY IS NOT NULL;


UPDATE LAYOFF.LAYOFF_WORK2 L1
SET INDUSTRY = L2.INDUSTRY
FROM LAYOFF.LAYOFF_WORK2 L2
WHERE L1.COMPANY = L2.COMPANY
  AND L1.LOCATION = L2.LOCATION
  AND L1.INDUSTRY IS NULL
  AND L2.INDUSTRY IS NOT NULL;


SELECT *
FROM LAYOFF.LAYOFF_WORK2
WHERE INDUSTRY IS NULL
  OR INDUSTRY = '';


SELECT *
FROM LAYOFF.LAYOFF_WORK2
WHERE TOTAL_LAID_OFF IS NULL
  AND PERCENTAGE_LAID_OFF IS NULL
  DELETE
  FROM LAYOFF.LAYOFF_WORK2 WHERE TOTAL_LAID_OFF IS NULL
  AND PERCENTAGE_LAID_OFF IS NULL;


ALTER TABLE LAYOFF.LAYOFF_WORK2
DROP COLUMN ROW_NUM;